version: '3'
services:
  nginx:
    restart: always
    container_name: graduate_nginx
    image: nginx
    network_mode: "host"
    ports:
      - "80:80"
    volumes:
     - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - $PWD/nginx:/var/log/nginx

  vue:
    build: ./vue
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./vue:/var/www/swi-vue/project/vue
      #- /var/www/swi-vue/project/vue/node_modules

  node:
    build: ./node-api
    restart: always
    ports:
      - "8070:8070"
    volumes:
      - ./node-api:/var/www/swi-vue/project/node-api
      - /var/www/swi-vue/project/node-api/node_modules
  # mysql:
  #   image: mysql:8
  #   ports:
  #    - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE:      intes
  #     MYSQL_USER:          admin
  #     MYSQL_PASSWORD:      admin
  #   volumes:
  #    - ./mysql:/var/lib/mysql
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #    - "8090:80"
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_PORT: 3306
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

networks:
  backend:
    driver: "bridge"