version: '3'
services:
  nginx:
    restart: always
    container_name: graduate_nginx
    build: ./vue
    ports:
      - "8080:80"
    volumes:
     - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
     - $PWD/nginx:/var/log/nginx
     - ./vue:/var/www/swi-vue/project/vue
     - /var/www/swi-vue/project/vue/node_modules
  node:
    build: ./node-api
    restart: always
    ports:
      - "8070:8070"
    volumes:
      - ./node-api:/var/www/swi-vue/project/node-api
      - /var/www/swi-vue/project/node-api/node_modules
  swipl:
    build: ./swipl
    restart: always
    ports:
      - "8060:8060"
    volumes:
      - ./prolog:/var/www/swi-vue/project/swipl
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
