version: '3'
services:
  nginx:
    restart: always
    container_name: sgups_nginx
    build: ./vue
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx:/var/log/nginx
      - ./vue:/var/www/html
  node:
    build: ./node-api
    container_name: sgups_nodejs
    restart: always
    ports:
      - "8070:8070"
    volumes:
      - ./node-api:/var/www/html/node-api
      - /var/www/html/node-api/node_modules
  swipl:
    build: ./swipl
    container_name: sgups_swipl
    restart: always
    ports:
      - "8060:8060"
    volumes:
      - ./prolog:/var/www/html/swipl
  mongo:
    image: mongo
    container_name: sgups_mongo
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  mongo-express:
    image: mongo-express
    container_name: sgups_mongoex
    restart: always
    ports:
      - "8090:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
